on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
name: Main Workflow
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/ru/r2cloud/
          ~/.sonar/cache
          ~/.rvm/
        key: ${{ runner.os }}-maven
        restore-keys: |
          ${{ runner.os }}-maven-
      
    - uses: actions/setup-java@v3
      with:
        distribution: 'liberica'
        java-version: '11'

    - name: Package
      run: mvn clean package
